print ("============================ Data Diri Siswa ===================================")
masukan_nama = input ("Masukan Nama Anda : ")
masukan_kelas_anda = int(input ("Masukan Nama Anda : "))
masukan_lokasi = input ("Masukan Lokasi Anda : ")
print ("===============================================================")
print ("nama anda", masukan_nama , "berhasil terevikasi")
print ("kelas anda adalah", masukan_lokasi, "sudah berhasil")
print ("Lokasi Anda Adalah " , masukan_lokasi)
print (f"masukan variable" ,  {masukan_kelas_anda} , {masukan_lokasi} , {masukan_nama})